<?xml version="1.0" ?>
<robot name="finger_with_stage"
    xmlns:xacro="https://ei.is.tuebingen.mpg.de/xacro">

    <xacro:include filename="finger_macro.urdf.xacro" />
    <xacro:include filename="macros.xacro" />

    <!-- Add the "stage" -->

    <!-- Meshes -->
    <xacro:property name="mesh_file_extension" value="stl"/>
    <xacro:property name="mesh_dir" value="package://robot_properties_manipulator/meshes/${mesh_file_extension}"/>
    <xacro:property name="stage_mesh" value="${mesh_dir}/BL-M_Table_ASM_big.${mesh_file_extension}"/>

    <link name="stage_link">
        <xacro:add_geometry
            origin_rpy="0 0 0"
            origin_xyz="0 0 0"
            mesh_file="${stage_mesh}"
            mesh_scale="0.001 0.001 0.001"/>
    </link>
    <!-- Finished adding the stage -->

    <!-- Define the global base_link and place stage relative to it. -->
    <link name="base_link" />

    <!-- Define the stage -->
    <joint name="base_to_stage" type="fixed">
        <parent link="base_link"/>
        <child link="stage_link"/>
        <origin xyz="0 0 0"/>
    </joint>

    <!-- Define the upper holder -->
    <link name="upper_holder_link" />
    <joint name="stage_to_upper_holder_joint" type="fixed">
        <parent link="stage_link"/>
        <child link="upper_holder_link"/>
        <origin xyz="0 0 0.34"/>
    </joint>

    <!-- Define the three fingers and place them relative to the upper holder -->
    <finger idx="_0"/>
    <finger idx="_120"/>
    <finger idx="_240"/>

    <xacro:property name="offset" value="0.04"/>
    <xacro:property name="angle1" value="${radians(0)}"/>
    <xacro:property name="angle2" value="${radians(120)}"/>
    <xacro:property name="angle3" value="${radians(240)}"/>

    <joint name="holder_to_finger_0" type="fixed">
        <parent link="upper_holder_link"/>
        <child link="finger_base_link_0"/>
        <origin xyz="${offset * sin(angle1)} ${offset * cos(angle1)} 0" rpy="0 0 0"/>
    </joint>

    <joint name="holder_to_finger_1" type="fixed">
        <parent link="upper_holder_link"/>
        <child link="finger_base_link_120"/>
        <origin xyz="${offset * sin(angle2)} ${offset * cos(angle2)} 0" rpy="0 0 ${radians(240)}"/>
    </joint>

    <joint name="holder_to_finger_2" type="fixed">
        <parent link="upper_holder_link"/>
        <child link="finger_base_link_240"/>
        <origin xyz="${offset * sin(angle3)} ${offset * cos(angle3)} 0" rpy="0 0 ${radians(120)}"/>
    </joint>

</robot>
